#!/bin/sh
#
# Initialize GPIO pins (LEDs)
#

. /etc/default/gpio

case "$1" in
	start)
		for i in $OUTPUTS; do
			#'low' is equiv. to setting direction=output, value=0 at once
			echo $i | sed 's/gpio//' > /sys/class/gpio/export
			echo low > /sys/class/gpio/$i/direction
		done

		for i in $INPUTS; do
			echo $i | sed 's/gpio//' > /sys/class/gpio/export
			echo in > /sys/class/gpio/$i/direction
		done

		#HACK: needed because there are built-in pull-up resistors, so we have to pull the pin to ground
		echo 1 > /sys/class/gpio/gpio0/active_low

		echo 1 > /sys/class/gpio/${GPIO_ERROR}/value
		;;
	stop|restart|reload)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
