#!/bin/sh

. /etc/default/gpio

case "$1" in
	start)
		if ifconfig wlan0 | grep -q -E '[0-9]+.[0-9]+.[0-9]+.[0-9]+' ; then
			/usr/bin/teapotd -B &> /dev/kmsg
		else
			echo "No IP address available"
			exit 1
		fi
		;;

	stop)
		echo 1 > /sys/class/gpio/${GPIO_ERROR}/value
		killall teapotd
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
